spring:
  redis:
    database: 0
    host: localhost
    username: ""
    password: ""
    port: 6379

#Can also run just redis using docker run -p 16379:6379 -d redis:6.0 redis-server --requirepass "mypass"
